main/views.py
'''
2016 wookieware.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.


__author__ = "@netwookie"
__credits__ = ["Rick Kauffman"]
__license__ = "Apache2"
__version__ = "1.0.0"
__maintainer__ = "Rick Kauffman"
__email__ = "rick@rickkauffman.com"
__status__ = "Prototype"

Flask script that manages strains and stores
'''
from flask import Blueprint, render_template, request, redirect, session, url_for, abort
import uuid
import os
from utilities.get_token import token
# rom test2.models import Creds

main_app = Blueprint('main_app', __name__)

@main_app.route('/main', methods=('GET', 'POST'))
@main_app.route('/', methods=('GET', 'POST'))
@main_app.route('/index', methods=('GET', 'POST'))
def main():
    ''' This section for any database preprocesses and capture login creds
    '''
    # Do any preprocessing here
    return render_template('main/main1.html')


@main_app.route('/main_select', methods=('GET', 'POST'))
def main_select():
    ''' This section to authenticate the user
    '''
    # Do any preprocessing here

    # Pull to submit form variables
    hostip=request.form['hostip']
    app_id=request.form['app_id']
    app_secret=request.form['app_secret']

    # Get token
    result = token(app_id,app_secret,hostip)
    # Check if 200
    if result[1] == 200:
        return render_template('main/main_leaf.html')
    else:
        error='FAILED_TO_LOGIN....TRY AGAIN!'
        return render_template('error/error.html', error=error)





@main_app.route('/help', methods=('GET', 'POST'))
def help():

    return render_template('main/help.html')

stores/views.py
'''
 April 2018 wookieware.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.


__author__ = "@netwookie"
__credits__ = ["Rick Kauffman"]
__license__ = "Apache2"
__version__ = "1.0.0"
__maintainer__ = "Rick Kauffman"
__email__ = "rick@rickkauffman.com"
__status__ = "Prototype"

Leaf - Graphical Ansible Workbench - stores manager - views
'''
#
'''
TODO: Fix the upload to look like template2
'''
#
#
from flask import Blueprint, render_template, request, redirect, session, url_for, abort, flash
import requests
import json


stores_app = Blueprint('stores_app', __name__)

@stores_app.route('/new', methods=('GET', 'POST'))
def new():
    """
    Adds a new stores to the stores database it offers user a window to type in a new stores.
    :param GET: The function returns a textbox to add new stores
    :param POST: The function will save the new stores to the database
    :return:GET a textbox, POST a database success/fail indication
    :rtype: Jinja template
    """

    return render_template('stores/newstore.html')

@stores_app.route('/list', methods=('GET', 'POST'))
def list():
    """
    Creates a list of all the storess in the stores database.
    :param GET: The function returns a list of storess
    :return:GET returns a list of storess.
    :rtype: Python Dictionary
    """
    from utilities.get_token import token
    stores='None'
    app_id='sample'
    app_secret='test'
    hostip='10.132.0.18'

    get_token = token(app_id,app_secret,hostip)
    token = get_token[0]

    # headers
    headers = {"Content-Type":"application/json", "X-APP-ID":app_id, "X-APP-TOKEN":token}

    # URL for requesting token
    # store_url = 'http://10.132.0.18:8088/stores/'
    store_url = 'http://'+hostip+':8088/stores/'

    # Make request
    stores = requests.get(store_url, headers=headers)
    stores = json.loads(stores.text)
    stores = stores['stores']

    print(stores)
    return render_template('stores/storelist.html', stores=stores)

@stores_app.route('/edit', methods=('GET', 'POST'))
def edit():
    """
    Select a stores by name and edit it's contents.
    :param GET: The function returns a list of stores names to a selector
    :param POST: The function displays the contents of the stores in a textbox
    :return:GET returns a list of stores names, POST presents stores details.
    :rtype: Jinja template
    """
    stores='None'
    return render_template('stores/storeseditselect.html', stores=stores)


@stores_app.route('/delete', methods=('GET', 'POST'))
def delete():
    """
    Delete a stores by name.
    :param GET: The function returns a list of stores names to a selector
    :param POST: The function displays the contents of the stores in a textbox
    :return:GET offers selection list, POST success or fail of the database delete
    :rtype: Jinja template
    """
    stores='None'
    return render_template('stores/storesdelete.html', stores=stores)

@stores_app.route('/bulk', methods=('GET', 'POST'))
def bulk():
    """
    Upload a stores from the users computer.
    :param GET: The function returns a list of stores names to a selector
    :param POST: The function displays the contents of the stores in a textbox
    :return:Get presents user with a Choose file button, POST uploads file to database
    :rtype: Jinja template
    """

    # Return file chooser
    return render_template('stores/storesupload.html')

@stores_app.route('/copy', methods=('GET', 'POST'))
def copy():
    """
    Copy a stores from the users computer.
    :param GET: The function returns a list of stores names to a selector
    :param POST: The function copies the selected stores to a new db record
    :return:Get presents user with a Choose file button, POST copies file to database
    :rtype: Jinja template
    """
    stores='None'
    return render_template('stores/storescopy.html', stores=stores)

strains/views.py
'''
 2016 wookieware..
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.


__author__ = "@netwookie"
__credits__ = ["Rick Kauffman"]
__license__ = "Apache2"
__version__ = "1.0.0"
__maintainer__ = "Rick Kauffman"
__email__ = "rick@rickkauffman.com"
__status__ = "Prototype"

Manages strain strain database
'''
from flask import Blueprint, render_template, request, redirect, session, url_for, abort, flash


strains_app = Blueprint('strains_app', __name__)

@strains_app.route('/strainnew', methods=('GET', 'POST'))
def strainnew():
    '''
    Adds a new strain strain to the strain database
    Reads form variables, creates a strain variable and
    saves it to the mongo database.
    '''

    return render_template('strain/newstrain.html', form=form)

@strains_app.route('/strainlist', methods=('GET', 'POST'))
def strainlist():
    '''
    Lists all the strain strains in the database
    '''

    return render_template('strain/strainlist.html', strain=strain)

@strains_app.route('/strainedit', methods=('GET', 'POST'))
def strainedit():
    '''
    Get selected strain from database and fill out edit form
    '''

    return render_template('strain/straineditselect.html', strain=strain)


@strains_app.route('/straindelete', methods=('GET', 'POST'))
def straindelete():
    '''
    Get selected strain strain from database and delete it
    '''

    return render_template('strain/straineditdelete.html', strain=strain)

@strains_app.route('/straincopy', methods=('GET', 'POST'))
def straincopy():
    '''
    Copy a strain
    '''

    return render_template('strain/straindbdrop.html')

@strains_app.route('/strainbulk', methods=('GET', 'POST'))
def strainbulk():
    '''
    Bulk Load the strain database
    '''


    return render_template('strain/bulkgood.html')

templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
  {{ field.label }}
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class="text-danger">
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
</div>
{% endmacro %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    


    <!--Bootsrap 4 CDN-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <!--Custom styles-->
    <link rel="stylesheet" type="text/css" href="styles.css">

    {% block header %}{% endblock %}
  </head>
  <body>

    <div class="container">

    {% block content %}{% endblock %}

      <div class="col-md-offset-3 col-md-6">
        <hr />
        <footer>
        2021 Wookieware
        </footer>
      </div>

    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-1.12.1.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    {% block end_body_js %}{% endblock %}

  </body>
</html>

templates/inventory.j2
{%  block inventory %}
[ spine ] {% for i in spine %}
{{ i }} {% endfor %}
[ leaf ] {% for i in leaf %}
{{ i }} {% endfor %}
{%  endblock %}

templates/main/main_leaf.html
{% extends "base.html" %}

{% block title %}Welcome to Paw Console{% endblock %}

{% block header %}<link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">{% endblock %}

{% block content %}



<div style="padding-left:16px">

    <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="container">

        <h1>PAW</h1>
        <img src="{{ url_for('static', filename='assets/pets.png') }}" width="600"  heights="90" />
        <h2>Managing Pets and Stores</h2>
        <p>A tool for working with a pet database and store locations</p>
        Version 0.1.0
        {% include "navbar_leaf2.html" %}
      </div>


{% endblock %}

templates/navbar2.html
<!-- Navigation bar-->

<div class="" id="home">
  <nav class="navbar navbar-expand-xl">
      <div class="container h-100">
        <div class="navbar-header">
        <a class="navbar-brand" href="{{ url_for('main_app.main') }}">
            <img alt="companion logo" width="80" height="80" src="{{ url_for('static', filename='assets/dog.PNG') }}"></a>
        Companion for Aruba Fabric Composer
        </div>
          <button class="navbar-toggler ml-auto mr-0" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <i class="fas fa-bars tm-nav-icon"></i>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="main_return">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="help">Help!</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://www.wookieware.com" class="navbar-link">About</a>
                </li>


            </ul>
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      User Log
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <a class="dropdown-item" href="#">Run An Action</a>
                      <a class="dropdown-item" href="#">Run An Action</a>
                      <a class="dropdown-item" href="#">Run An Action</a>
                      <a class="dropdown-item" href="#">Run An Action</a>

                    </div>
                </li>


                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      StackStorm
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Run An Action</a>
                        <a class="dropdown-item" href="#">Run An Action</a>
                        <a class="dropdown-item" href="#">Run An Action</a>
                        <a class="dropdown-item" href="#">Run An Action</a>


                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      CFM API
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Run An Action</a>
                    <a class="dropdown-item" href="#">Run An Action</a>
                    <a class="dropdown-item" href="#">Run An Action</a>
                    <a class="dropdown-item" href="#">Run An Action</a>
                    <a class="dropdown-item" href="#">Run An Action</a>
                    </div>
                </li>
            </ul>
          </div>
      </div>

  </nav>
</div>

templates/navbar_leaf.html
<nav class="navbar">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-left">
              <div class="row">
                <ul class="nav nav-tabs">

                  <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Stores
                       <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="{{ url_for('stores_app.new') }}">New</a></li>
                        <li><a href="{{ url_for('stores_app.list') }}">List</a></li>
                        <li><a href="{{ url_for('stores_app.edit') }}">Edit</a></li>
                        <li><a href="{{ url_for('stores_app.delete') }}">Delete</a></li>
                        <li><a href="{{ url_for('stores_app.bulk') }}">Bulk Load</a></li>
                        <li><a href="{{ url_for('stores_app.copy') }}">Copy</a></li>
                      </ul>
                  </li>
                  <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Strains
                       <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="{{ url_for('strains_app.strainnew') }}">New</a></li>
                        <li><a href="{{ url_for('strains_app.strainlist') }}">List</a></li>
                        <li><a href="{{ url_for('strains_app.straindelete') }}">Delete</a></li>
                        <li><a href="{{ url_for('strains_app.strainedit') }}">Edit</a></li>
                        <li><a href="{{ url_for('strains_app.strainbulk') }}">Bulk Load</a></li>
                        <li><a href="{{ url_for('strains_app.straincopy') }}">Copy</a></li>
                      </ul>
                  </li>

                   <li>
                       <a href="http://www.wookieware.com" class="navbar-link">About</a></p>
                   </li>
                   <li>
                       <a href="help" class="navbar-link">Help!</a></p>
                   </li>

              </ul>
            </ul>
        </div>
    </div>
</nav>

templates/navbar_leaf2.html
<nav class="navbar">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-left">
              <div class="row">
                <ul class="nav nav-tabs">

                  <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Stores
                       <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="{{ url_for('stores_app.new') }}">New</a></li>
                        <li><a href="{{ url_for('stores_app.list') }}">List</a></li>
                        <li><a href="{{ url_for('stores_app.edit') }}">Edit</a></li>
                        <li><a href="{{ url_for('stores_app.delete') }}">Delete</a></li>
                        <li><a href="{{ url_for('stores_app.bulk') }}">Bulk Load</a></li>
                        <li><a href="{{ url_for('stores_app.copy') }}">Copy</a></li>
                      </ul>
                  </li>
                  <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Pets
                       <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="{{ url_for('strains_app.strainnew') }}">New</a></li>
                        <li><a href="{{ url_for('strains_app.strainlist') }}">List</a></li>
                        <li><a href="{{ url_for('strains_app.straindelete') }}">Delete</a></li>
                        <li><a href="{{ url_for('strains_app.strainedit') }}">Edit</a></li>
                        <li><a href="{{ url_for('strains_app.strainbulk') }}">Bulk Load</a></li>
                        <li><a href="{{ url_for('strains_app.straincopy') }}">Copy</a></li>
                      </ul>
                  </li>

                   <li>
                       <a href="http://www.wookieware.com" class="navbar-link">About</a></p>
                   </li>
                   <li>
                       <a href="help" class="navbar-link">Help!</a></p>
                   </li>

              </ul>
            </ul>
        </div>
    </div>
</nav>

templates/stores/choosewarning.html
{% extends "base.html" %}

{% block title %}Error{% endblock %}

{% block content %}

{% include "navbar_leaf.html" %}

<div class="col-xs-10">
    <h3>Please select a real project and not the default Choose</h3>
    <h2> Error Message : {{ error }}</h2>

  </div>

</div>
{% endblock %}

templates/stores/dberror.html
{% extends "base.html" %}

{% block title %}Error{% endblock %}

{% block content %}

{% include "navbar_leaf.html" %}

<div class="col-xs-10">
    <h3>Error writing to database!</h3>
    <h2> Error Message : {{ error }}</h2>

  </div>

</div>
{% endblock %}

templates/stores/deleteplaybook.html
{% extends "base.html" %}

{% block title %}Record Update{% endblock %}

{% block content %}

{% include "navbar_leaf.html" %}

<div class="col-xs-10">

    <h3>Delete Playbook Record</h3>
    <form action = "{{ url_for('main_app.main') }}" method = "get">
    <h2> Playbook successfully deleted from the database!</h2>
    <p> Please return to the main menu </p>


  </div>
</from>
<hr>
<button type="submit" class="btn btn-success btn-sm btn-block">Main Menu</button>

</div>
{% endblock %}

templates/stores/generalsuccess.html
{% extends "base.html" %}

{% block title %}Success{% endblock %}

{% block header %}<link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">{% endblock %}

{% block content %}

{% include "navbar_leaf.html" %}

<div class="row">

<h2> Success</h2>
<form action = "{{ url_for('main_app.main') }}" method = "get">
  {{ success }}

    <hr>
    <p> Please retun to main menu </p>
</from>
<hr>
<button type="submit" class="btn btn-success btn-sm btn-block">Main Menu</button>
{% endblock %}

templates/stores/inventorywarning.html
{% extends "base.html" %}

{% block title %}Error{% endblock %}

{% block content %}

{% include "navbar_leaf.html" %}

<div class="col-xs-10">
    <h3>Inventory is required before adding playbooks, templates or projects</h3>
    <h2> Error Message : {{ error }}</h2>

  </div>

</div>
{% endblock %}

templates/stores/savedplaybook.html
{% extends "base.html" %}

{% block title %}Saved{% endblock %}

{% block content %}

{% include "navbar_leaf.html" %}

<div class="col-xs-10">
    <h3>Create New Playbook</h3>
  <form action = "{{ url_for('main_app.main') }}" method = "get">
    <h2>Playbook successfully written to database!</h2>
    <p> Please return to the main menu </p>


  </div>
</from>
<hr>
<button type="submit" class="btn btn-success btn-sm btn-block">Main Menu</button>
</div>
{% endblock %}

templates/stores/storelist.html
{% extends "base.html" %}

{% block title %}List Stores{% endblock %}

{% block header %}<link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">{% endblock %}

{% block content %}

{% include "navbar_leaf2.html" %}

<div class="row">

<h2> Store List</h2>
<form action = "{{ url_for('main_app.main') }}" method = "get">
<div class="container">

  <table class="table">
   <thead><tr>
    <th>Name</th><th>Neighborhood</th><th>Street</th><th>City</th><th>State</th><th>Zip</th><th>Phone</th>
  </tr></thead>
  <tbody>
  {% for i in stores %}
    <tr>
      <td>{{ i.name }}</td>
      <td>{{ i.neighborhood }}</td>
      <td>{{ i.street_address }}</td>
      <td>{{ i.city }}</td>
      <td>{{ i.state }}</td>
      <td>{{ i.zip }}</td>
      <td>{{ i.phone }}</td>
    </tr>
  </tbody>

     {% endfor %}
    </table>
</div>
    <hr>
    <p> Please retun to main menu </p>
</form>
<hr>
<button type="submit" class="btn btn-success btn-sm btn-block">Main Menu</button>
{% endblock %}

templates/stores/updatedproject.html
{% extends "base.html" %}

{% block title %}Record Update{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="col-xs-10">

    <h3>Update POD Record</h3>
    <form action = "{{ url_for('main_app.main') }}" method = "get">
    <h2> POD successfully updated in database!</h2>
    <p> Please return to the main menu </p>


  </div>
</from>
<hr>
<button type="submit" class="btn btn-primary btn-sm btn-block">Main Menu</button>

</div>
{% endblock %}

templates/strain/deleteswitch.html
{% extends "base.html" %}

{% block title %}Record Update{% endblock %}

{% block content %}

{% include "navbar_leaf.html" %}

<div class="col-xs-10">

    <h3>Delete Switch Record</h3>
    <form action = "{{ url_for('main_app.main') }}" method = "get">
    <h2> Switch successfully deleted from the database!</h2>
    <p> Please return to the main menu </p>


  </div>
</from>
<hr>
<button type="submit" class="btn btn-success btn-sm btn-block">Main Menu</button>

</div>
{% endblock %}

templates/strain/dropswitch.html
{% extends "base.html" %}

{% block title %}Common{% endblock %}

{% block content %}

{% include "navbar_leaf.html" %}

<div class="col-xs-10">
    <h3>Save edit switch</h3>
  <form action = "{{ url_for('main_app.main') }}" method = "get">
    <h2> Switch Database Has Been Dropped</h2>
    <p> Please return to the main menu </p>


  </div>
</from>
<hr>
<button type="submit" class="btn btn-success btn-sm btn-block">Main Menu</button>
</div>
{% endblock %}

templates/strain/savedswitch.html
{% extends "base.html" %}

{% block title %}Common{% endblock %}

{% block content %}

{% include "navbar_leaf.html" %}

<div class="col-xs-10">
    <h3>Save switch</h3>
  <form action = "{{ url_for('main_app.main') }}" method = "get">
    <h2> Switch successfully updated!</h2>
    <p> Please return to the main menu </p>


  </div>
</from>
<hr>
<button type="submit" class="btn btn-success btn-sm btn-block">Main Menu</button>
</div>
{% endblock %}

templates/strain/switchdisplay.html
{% extends "base.html" %}

{% block title %}Ansible Inventory{% endblock %}

{% block header %}<link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">{% endblock %}

{% block content %}

{% include "navbar_leaf.html" %}

<div class="row">

<h2> Inventory for {{ pod }}</h2>
<form action = "{{ url_for('main_app.main') }}" method = "get">
  <textarea class="form-control" rows="15"  name={{pod}}>
    [ spine ] {% for i in spine %}
    {{ i }} {% endfor %}
    [ leaf ] {% for i in leaf %}
    {{ i }} {% endfor %}
    [ edge ] {% for i in edge %}
    {{ i }} {% endfor %}
    [ distribution ] {% for i in distribution %}
    {{ i }} {% endfor %}
    [ database ] {% for i in database %}
    {{ i }} {% endfor %}
    [ loadbalancer ] {% for i in loadbalancer %}
    {{ i }} {% endfor %}
    [ webserver ] {% for i in webserver %}
    {{ i }} {% endfor %}
  </textarea>


    <hr>
    <p> Please retun to main menu </p>
</from>
<hr>
<button type="submit" class="btn btn-success btn-sm btn-block">Main Menu</button>
{% endblock %}

templates/strain/switchlist.html
{% extends "base.html" %}

{% block title %}Switch List{% endblock %}

{% block header %}<link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">{% endblock %}

{% block content %}

{% include "navbar_leaf.html" %}

<div class="row">

<h2> Switch Inventory</h2>
<form action = "{{ url_for('main_app.main') }}" method = "get">
<div class="container">
  <table class="table">
     <thead>
       <tr>
         <th>Project Name</th><th>Mgmt IP Address</th><th>Role</th><th>Model</th><th>Host</th>
       </tr>
     </thead>
     <tbody>
           {% for i in switch %}
         <tr>
           <td>{{ i.pod }}</td>
            <td>{{ i.mgmt_ip }}</td>
             <td>{{ i.role }}</td>
              <td>{{ i.model }}</td>
              <td>{{ i.host }}</td>
         </tr>
          {% endfor %}
     </tbody>
  </table>


</div>
    <hr>
    <p> Please retun to main menu </p>
</form>
<hr>
<button type="submit" class="btn btn-success btn-sm btn-block">Main Menu</button>
{% endblock %}

templates/strain/updatedswitch.html
{% extends "base.html" %}

{% block title %}Record Update{% endblock %}

{% block content %}

{% include "navbar_leaf.html" %}

<div class="col-xs-10">

    <h3>Update Switch Record</h3>
    <form action = "{{ url_for('main_app.main') }}" method = "get">
    <h2> Switch successfully updated in database!</h2>
    <p> Please return to the main menu </p>


  </div>
</from>
<hr>
<button type="submit" class="btn btn-success btn-sm btn-block">Main Menu</button>

</div>
{% endblock %}